/**
 * Generate the preview entry for a project that is not this one.
 *
 * The entry imports the project's *real* view surfaces by absolute path. A
 * preview that rendered a copy, or a mock, would let a designer tinker with
 * something that is not the thing — and the whole loop depends on what they
 * move being what ships.
 */
import fs from 'node:fs'
import path from 'node:path'
import type { Manifest } from '../schema'

export interface GeneratedPreview {
  dir: string
  entry: string
  html: string
  views: string[]
  missing: string[]
}

export function generatePreview(
  manifest: Manifest,
  root: string,
  packageRoot: string,
  outDir = '.slots/preview',
): GeneratedPreview {
  const dir = path.join(root, outDir)
  fs.mkdirSync(dir, { recursive: true })

  const views: string[] = []
  const missing: string[] = []
  const imports: string[] = []
  const entries: string[] = []

  for (const [viewId, surface] of Object.entries(manifest.viewSurfaces ?? {})) {
    const abs = path.resolve(root, surface.file)
    if (!fs.existsSync(abs)) {
      missing.push(`${viewId}: ${surface.file}`)
      continue
    }
    const alias = `V${views.length}`
    // Extensionless, because a bundler resolves it and TS would reject `.tsx`.
    const spec = abs.replace(/\.tsx?$/, '')
    imports.push(`import { ${surface.component} as ${alias} } from ${JSON.stringify(spec)}`)
    entries.push(`  ${JSON.stringify(viewId)}: ${alias},`)
    views.push(viewId)
  }

  const manifestPath = path.resolve(root, '.slots/manifest.json')
  const entry = path.join(dir, 'main.tsx')
  fs.writeFileSync(
    entry,
    `/* GENERATED by \`slots preview\` — do not edit, do not commit. */
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Preview } from ${JSON.stringify(path.join(packageRoot, 'src/preview/Preview'))}
import manifest from ${JSON.stringify(manifestPath)}
${imports.join('\n')}

const surfaces = {
${entries.join('\n')}
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <Preview manifest={manifest as never} surfaces={surfaces as never} />
  </StrictMode>,
)
`,
  )

  const html = path.join(dir, 'index.html')
  fs.writeFileSync(
    html,
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>slots · preview</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./main.tsx"></script>
  </body>
</html>
`,
  )

  // The generated directory is build output living inside someone's repo.
  fs.writeFileSync(path.join(dir, '.gitignore'), '*\n')

  return { dir, entry, html, views, missing }
}
