/**
 * `npm run identity` — the favicon and the mark, projected from the record.
 *
 * Two files, both regenerable, neither edited by hand: `public/favicon.svg`,
 * the whole system at 32px — one contour and a point for the present — and
 * `src/identity/mark.svg`, the same state at four levels. They are what the
 * record projects at the moment this ran; `npm run build` runs it again, so
 * the deployed icon is the deployed record. Same engine as the page, same
 * derivation, same lines: `@strata/identity`, the package beside the engine.
 *
 *   node --import tsx/esm scripts/emit-identity.ts [root]
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { readAll, seedsInForce } from '@strata/substrate/log'
import { OBSIDIAN } from '../src/theme/generateTheme'
import { grounds, readLedger } from '../src/theme/emit'
import { generateTheme } from '../src/theme/generateTheme'
import { themeTokens } from '../src/theme/ledger'
import { oklchToRgb, parseOklch } from '../src/theme/color'
import { frameAt, levelCount } from '@strata/identity/field'
import { stateFrom } from '@strata/identity/record'
import { svgFrom } from '@strata/identity/render'
import { paletteFrom } from '../src/identity/palette'

export const FAVICON_PATH = 'public/favicon.svg'
export const MARK_PATH = 'src/identity/mark.svg'
export const HERO_PATHS = { light: 'public/hero-light.svg', dark: 'public/hero-dark.svg' } as const

/** 2:1 — what a repository's social card is, and what the field spreads across here. */
export const HERO = { height: 640, aspect: 2 } as const

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

/**
 * OKLCH resolved to a hex triple, because this file is read by things that
 * are not browsers. Every other projection keeps `oklch()` — a stylesheet is
 * read by a browser, and the wide gamut is the point. A social card is
 * rasterised by link unfurlers and by GitHub's own card renderer, and a
 * colour one of them cannot parse is an image that arrives blank.
 */
function hex(css: string): string {
  const c = parseOklch(css)
  if (!c) return css
  const [r, g, b] = oklchToRgb(c.L, c.C, c.H)
  const two = (v: number) => Math.round(v * 255).toString(16).padStart(2, '0')
  const rgb = `#${two(r)}${two(g)}${two(b)}`
  return c.alpha < 1 ? `${rgb}${two(c.alpha)}` : rgb
}

/**
 * THE HERO — the record, drawn as a field, at the one size a repository shows
 * a stranger.
 *
 * It is a projection like the favicon and the mark: the same engine, the same
 * derivation, the same lines, regenerated by every build. What the product
 * adds here is the only thing the engine has no business knowing — its own
 * name, and a label that says what the picture is. The label is the count of
 * decisions on the record, because the honest caption for a picture of a
 * record is how much of it there is.
 *
 * Two files rather than one with a media query: GitHub strips the <style> a
 * themed SVG needs, so the README picks the ground with <picture> and each
 * file carries its own. Both grounds are the house's own two poles.
 */
export function heroSvg(field: string, pal: { ink: string; muted: string; faint: string; ground: string }, decisions: number): string {
  const W = HERO.height * HERO.aspect
  const H = HERO.height
  // The field is the picture; the frame stays quiet over it. Left-aligned and
  // low, the way the identity page sets the same two lines.
  const inner = field
    .slice(field.indexOf('>', field.indexOf('<svg')) + 1)
    .replace('</svg>', '')
    .replace(/<style>.*?<\/style>/, '')
    // The field draws in `var(--ink)`, which the stripped <style> defined.
    .replaceAll('var(--ink)', pal.ink)
  const label = `${decisions} DECISIONS · THE RECORD, DRAWN AS A FIELD`
  const face = "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', Inter, system-ui, sans-serif"
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="Strata — the record, drawn as a field">
<rect width="${W}" height="${H}" fill="${pal.ground}"/>
${inner}
<text x="96" y="432" font-family="${esc(face)}" font-size="88" font-weight="700" letter-spacing="-2.2" fill="${pal.ink}">Strata</text>
<text x="96" y="486" font-family="${esc(face)}" font-size="25" font-weight="400" fill="${pal.muted}">A persistent structure. Changing expressions. Memory of what came before.</text>
<text x="96" y="546" font-family="${esc(face)}" font-size="13" font-weight="700" letter-spacing="1.9" fill="${pal.faint}">${esc(label)}</text>
</svg>
`
}

export function emitIdentity(root: string): Record<string, string> {
  const ledger = readLedger(root)
  const record = readAll(root)
  const state = stateFrom(record)
  // The theme in force is the record's — the same fold every projection reads.
  const seeds = grounds(seedsInForce(record, OBSIDIAN))
  const house = paletteFrom(seeds.house, ledger)
  const inks = { dark: paletteFrom(seeds.dark, ledger).ink, light: paletteFrom(seeds.light, ledger).ink, house: seeds.house.appearance }
  const base = { energy: seeds.house.energy, density: seeds.house.density }
  const favicon = svgFrom(frameAt(state, Infinity, { ...base, n: 24, levels: levelCount('favicon', seeds.house.density) }), 32, house, { dot: true, inks })
  const mark = svgFrom(frameAt(state, Infinity, { ...base, n: 64, levels: levelCount('mark', seeds.house.density) }), 160, house, { dot: false, inks })

  // The hero, on both grounds. The field is drawn wide — the engine spreads
  // its positions across the aspect and keeps the kernels circular — and each
  // file carries the ground it is for.
  const wide = frameAt(state, Infinity, { ...base, aspect: HERO.aspect, n: 96, levels: levelCount('mark', seeds.house.density) })
  const hero = (ground: 'light' | 'dark') => {
    const pal = paletteFrom(ground === 'light' ? seeds.light : seeds.dark, ledger)
    const tokens = themeTokens(generateTheme(ground === 'light' ? seeds.light : seeds.dark), ledger, 'value')
    return heroSvg(svgFrom(wide, HERO.height, pal, { dot: false }), { ink: hex(pal.ink), muted: hex(tokens['--ink-muted']), faint: hex(tokens['--ink-faint']), ground: hex(pal.ground) }, record.length)
  }
  const files = { [FAVICON_PATH]: favicon, [MARK_PATH]: mark, [HERO_PATHS.light]: hero('light'), [HERO_PATHS.dark]: hero('dark') }
  for (const [rel, text] of Object.entries(files)) {
    mkdirSync(dirname(join(root, rel)), { recursive: true })
    writeFileSync(join(root, rel), text)
  }
  return files
}

const invoked = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (invoked) {
  const root = process.argv[2] ? resolve(process.argv[2]) : join(dirname(fileURLToPath(import.meta.url)), '..')
  const files = emitIdentity(root)
  const n = readAll(root).length
  console.log(`emitted ${Object.keys(files).join(' and ')} from ${n} decision(s) on the record`)
}
