/**
 * `npm run social-card` — the hero as a PNG, for the one place that will not
 * take an SVG.
 *
 * GitHub's social preview is uploaded by hand in the repository's settings and
 * must be a raster, 1280×640. Everything else about the identity is a
 * projection regenerated by every build; this cannot be, because nothing here
 * can reach that setting. So the script is the projection and the PNG is a
 * again: run it, upload what it writes, and the card is the record as it
 * stood when you did.
 *
 * Headless Chrome over the DevTools protocol, with no dependency added — the
 * same renderer that draws the SVG everywhere else, so the raster and the
 * vector cannot disagree.
 *
 *   node scripts/social-card.mjs public/hero-light.svg out.png
 */
import { spawn } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { setTimeout as wait } from 'node:timers/promises'

// The browser this machine has. CHROME overrides it; on Linux the usual name
// is `google-chrome` or `chromium` on the PATH.
const CHROME = process.env.CHROME ?? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
const [, , svgPath, outPath] = process.argv
if (!svgPath || !outPath) {
  console.error('usage: node scripts/social-card.mjs <hero.svg> <out.png>')
  process.exit(1)
}
// Chrome writes a profile wherever it is told to. Pointed at the output path
// it wrote one into the repository, and the tidy-up at the end only ran when
// nothing threw — so a failed run left a browser profile behind, and eleven of
// its files were committed and dirtied every `git status` afterwards. It goes
// where temporary things go, and is removed whether this succeeds or not.
const profile = mkdtempSync(join(tmpdir(), 'strata-social-card-'))
const page = join(profile, 'card.html')
const done = () => rmSync(profile, { recursive: true, force: true })
process.on('exit', done)
writeFileSync(page, `<style>html,body{margin:0;padding:0}svg{display:block}</style>${readFileSync(svgPath, 'utf8')}`)

const PORT = 9400 + Math.floor(Math.random() * 500)
const chrome = spawn(
  CHROME,
  ['--headless=new', '--disable-gpu', '--hide-scrollbars', '--no-first-run', '--no-default-browser-check', `--user-data-dir=${join(profile, 'chrome')}`, `--remote-debugging-port=${PORT}`, '--window-size=1280,640', 'about:blank'],
  { stdio: 'ignore' },
)
const get = async (path) => {
  for (let i = 0; i < 150; i++) {
    await wait(120)
    try {
      return await (await fetch(`http://127.0.0.1:${PORT}${path}`)).json()
    } catch {}
  }
  return null
}
const list = await get('/json/list')
const target = list?.find((t) => t.type === 'page')?.webSocketDebuggerUrl
if (!target) { chrome.kill(); throw new Error('no page target') }

const ws = new WebSocket(target)
let id = 0
const pending = new Map()
ws.addEventListener('message', (e) => {
  const m = JSON.parse(e.data)
  if (m.id && pending.has(m.id)) pending.get(m.id)(m), pending.delete(m.id)
})
await new Promise((r) => ws.addEventListener('open', r))
const send = (method, params = {}) => new Promise((res) => { const n = ++id; pending.set(n, res); ws.send(JSON.stringify({ id: n, method, params })) })

await send('Page.enable')
await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 640, deviceScaleFactor: 1, mobile: false })
await send('Page.navigate', { url: 'file://' + page })
await wait(1500)
const shot = await send('Page.captureScreenshot', { format: 'png', clip: { x: 0, y: 0, width: 1280, height: 640, scale: 1 } })
if (shot.error || !shot.result?.data) { chrome.kill(); throw new Error('capture failed: ' + JSON.stringify(shot.error ?? shot)) }
writeFileSync(outPath, Buffer.from(shot.result.data, 'base64'))
ws.close()
chrome.kill()
done()
console.log(`${outPath} — 1280×640, from ${svgPath}`)
